### ISSUE TITLE
Need support for latest liquibase cli 4.4.0

### ISSUE THREAD

**Issue by RajarsiGit** [liquibase/node-liquibase#36]
### Description

Node-Liquibase installs Liquibase CLI 4.3.5 even if we have the latest version that is 4.4.0. Please look into this issue. Thanks.

**Expected behavior:** Should install Liquibase CLI 4.4.0

**Actual behavior:** Install CLI 4.3.5

**Comment by tabuckner** [comment]
@RajarsiGit I've published the new package but it will take some time to show up in NPM. 

I'll mention you again when I see it available.

**Comment by tabuckner** [comment]
@RajarsiGit https://www.npmjs.com/package/liquibase/v/4.4.0
