### ISSUE TITLE
not able to generate changeLog with new version

### ISSUE THREAD

**Issue by pavanjava** [liquibase/node-liquibase#39]
### Context
with new version of Liquibase
#### Node-Liquibase Version
4.4.0
### Description

when i configure the liquibase to run the generate changelog i fee the below error.

### Steps to Reproduce

1. liquibase --changeLogFile="./db-changelog.yaml" --url="jdbc:postgresql://localhost:5432/postgres" --username="postgres" --password="postgres" --classpath="postgresql-42.2.8.jar" --liquibaseSchemaName="user_mgmt" --logLevel="info" generateChangeLog  --dataOutputDirectory="" --defaultCatalogName="" --defaultSchemaName="" --diffTypes="" --includeCatalog=false --includeSchema=false --includeTablespace=false --outputSchemaAs=undefined --schemas=undefined 

**Expected behavior:
Should Generate Changelog

**Actual behavior:
Errored out.

Error: Command failed: liquibase --changeLogFile="./db-changelog.yaml" --url="jdbc:postgresql://localhost:5432/postgres" --username="postgres" --password="postgres" --classpath="postgresql-42.2.8.jar" --liquibaseSchemaName="user_mgmt" --logLevel="info" generateChangeLog  --dataOutputDirectory="" --defaultCatalogName="" --defaultSchemaName="" --diffTypes="" --includeCatalog=false --includeSchema=false --includeTablespace=false --outputSchemaAs=undefined --schemas=undefined 
Unexpected argument(s): --defaultCatalogName=, --defaultSchemaName=, --includeCatalog=false, --includeSchema=false, --includeTablespace=false, --outputSchemaAs=undefined

**Comment by tabuckner** [comment]
hey @pavanjava I feel like there's part of the error message that is missing here, but that might be part of the bug we're seeing.

If so i'm sure @nvoxland would want to know about the less-than-helpful error message here. 

Could you provide us more information about your project setup and how you're using it?

Are you using `node-liquibase` as a CLI tool?
Are you running it programmatically?
Can you try running it with `logLevel=debug`?

**Comment by tabuckner** [comment]
Hey @pavanjava I'd like to resolve this issue for you. Can you take a look at my previous question?

**Comment by pavanjava** [comment]
> Hey @pavanjava I'd like to resolve this issue for you. Can you take a look at my previous question?

Hey, sorry i was hooked with some other tasks and was not watching my git. Will try again and get your question answered.
